http:
  address: ":8080"

database:
  connection_string: ""

telemetry:
  enabled: false
  service_name: "books-service"
  environment: "local"
  otlp_endpoint: "otel-collector:4318"
  application_insights_connection_string: ""
